[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "fastapi>=0.120.1",
    "openai>=2.6.1",
    "pydantic>=2.12.3",
    "python-pptx>=1.0.2",
    "requests>=2.32.5",
    "uvicorn[standard]>=0.38.0",
]
